-- CreateTable
CREATE TABLE "activity_procurement" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "activityId" TEXT NOT NULL,
    "procurementProcessId" TEXT NOT NULL,
    "relationship" TEXT NOT NULL DEFAULT 'REQUIRED',
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "activity_procurement_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "activities" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "activity_procurement_procurementProcessId_fkey" FOREIGN KEY ("procurementProcessId") REFERENCES "procurement_processes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "pacc_schedules" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "procurementProcessId" TEXT NOT NULL,
    "scheduledPhase" TEXT NOT NULL,
    "phaseName" TEXT NOT NULL,
    "plannedStartDate" DATETIME NOT NULL,
    "plannedEndDate" DATETIME NOT NULL,
    "actualStartDate" DATETIME,
    "actualEndDate" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "responsibleUserId" TEXT,
    "milestones" TEXT,
    "dependencies" TEXT,
    "criticalPath" BOOLEAN NOT NULL DEFAULT false,
    "estimatedDuration" INTEGER,
    "actualDuration" INTEGER,
    "compliancePercentage" REAL NOT NULL DEFAULT 0,
    "risks" TEXT,
    "observations" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "pacc_schedules_procurementProcessId_fkey" FOREIGN KEY ("procurementProcessId") REFERENCES "procurement_processes" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "pacc_schedules_responsibleUserId_fkey" FOREIGN KEY ("responsibleUserId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "pacc_compliances" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "evaluationPeriod" TEXT NOT NULL,
    "periodType" TEXT NOT NULL,
    "fiscalYear" INTEGER NOT NULL,
    "totalProcesses" INTEGER NOT NULL DEFAULT 0,
    "processesOnSchedule" INTEGER NOT NULL DEFAULT 0,
    "processesDelayed" INTEGER NOT NULL DEFAULT 0,
    "processesAtRisk" INTEGER NOT NULL DEFAULT 0,
    "processesCancelled" INTEGER NOT NULL DEFAULT 0,
    "scheduledMilestones" INTEGER NOT NULL DEFAULT 0,
    "achievedMilestones" INTEGER NOT NULL DEFAULT 0,
    "delayedMilestones" INTEGER NOT NULL DEFAULT 0,
    "milestoneComplianceRate" REAL NOT NULL DEFAULT 0,
    "averageDelay" REAL NOT NULL DEFAULT 0,
    "criticalPathCompliance" REAL NOT NULL DEFAULT 0,
    "budgetCompliance" REAL NOT NULL DEFAULT 0,
    "legalComplianceScore" REAL NOT NULL DEFAULT 0,
    "timelinessScore" REAL NOT NULL DEFAULT 0,
    "qualityScore" REAL NOT NULL DEFAULT 0,
    "overallScore" REAL NOT NULL DEFAULT 0,
    "complianceGrade" TEXT,
    "keyFindings" TEXT,
    "recommendations" TEXT,
    "actionPlan" TEXT,
    "riskFactors" TEXT,
    "mitigationMeasures" TEXT,
    "evaluatedBy" TEXT,
    "approvedBy" TEXT,
    "evaluationDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvalDate" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "pacc_compliances_evaluatedBy_fkey" FOREIGN KEY ("evaluatedBy") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "pacc_compliances_approvedBy_fkey" FOREIGN KEY ("approvedBy") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "pacc_alerts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "alertType" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "procurementProcessId" TEXT,
    "scheduleId" TEXT,
    "triggerDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dueDate" DATETIME,
    "resolvedDate" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'ACTIVA',
    "priority" TEXT NOT NULL DEFAULT 'MEDIA',
    "affectedMilestones" TEXT,
    "potentialImpact" TEXT,
    "suggestedActions" TEXT,
    "assignedTo" TEXT,
    "createdBy" TEXT NOT NULL,
    "escalatedTo" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "requiresApproval" BOOLEAN NOT NULL DEFAULT false,
    "notificationSent" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "pacc_alerts_procurementProcessId_fkey" FOREIGN KEY ("procurementProcessId") REFERENCES "procurement_processes" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "pacc_alerts_scheduleId_fkey" FOREIGN KEY ("scheduleId") REFERENCES "pacc_schedules" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "pacc_alerts_assignedTo_fkey" FOREIGN KEY ("assignedTo") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "pacc_alerts_escalatedTo_fkey" FOREIGN KEY ("escalatedTo") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "pacc_reports" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reportType" TEXT NOT NULL,
    "reportPeriod" TEXT NOT NULL,
    "fiscalYear" INTEGER NOT NULL,
    "executiveSummary" TEXT,
    "performanceMetrics" TEXT,
    "processesAnalysis" TEXT,
    "achievedMilestones" TEXT,
    "pendingMilestones" TEXT,
    "riskAssessment" TEXT,
    "budgetStatus" TEXT,
    "legalCompliance" TEXT,
    "recommendations" TEXT,
    "nextPeriodPlanning" TEXT,
    "generatedBy" TEXT,
    "approvedBy" TEXT,
    "generationDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvalDate" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "pacc_reports_generatedBy_fkey" FOREIGN KEY ("generatedBy") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "pacc_reports_approvedBy_fkey" FOREIGN KEY ("approvedBy") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'INFO',
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "data" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "readAt" DATETIME,
    CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "activity_procurement_activityId_procurementProcessId_key" ON "activity_procurement"("activityId", "procurementProcessId");
